title: Lucien TITO
logo: /assets/img/0V1A18692.png
description: As a Computer Vision Engineer, I develop algorithms that help machines interpret visual information using deep learning and YOLO. I optimize models for real-time performance and deploy solutions that enhance user experiences in applications like autonomous systems and medical imaging.
show_downloads: true
theme: jekyll-theme-minimal
