title: Lucien TITO
logo: /assets/img/moi.png
#description: text below image
show_downloads: False
theme: jekyll-theme-minimal

# Contact Links
email: mailto:titovlucien@gmail.com
linkedin: https://www.linkedin.com/in/lucientito/
upwork: https://www.upwork.com/freelancers/~01ce60a3ef63722b23?mp_source=share
